#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.4.1f1_e6c045e14e4e"
#define UNITY_VERSION_FULL_NICE "2019.4.1f1 (e6c045e14e4e)"
#define UNITY_VERSION_BLD 15122501
#define UNITY_VERSION_DATE 1592425912
#define UNITY_VERSION_WIN "2019.4.1.15122501"
#define UNITY_VERSION_BRANCH "2019.4/release"
